name: HACS validation

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "23 5 * * 1"

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hacs/action@main
        with:
          category: integration
